image: ubuntu:latest
workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: always


job1:
  stage: build
  variables:
    TAG_LATEST: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:latest
    TAG_COMMIT: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHORT_SHA
  script:
    - echo "Building the app"
    - ssh -i $pkey azureuser@$ip
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker image ls
      
