image: ubuntu:latest
workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: always

job1:
  stage: build
  script:
    - echo "Building the app"
    - apt-get update -y
    - su
    - image ls
      
