image: docker:20.10

workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: always

services:
  - docker:20.10-dind

variables:
  DOCKER_IMAGE: "${CI_COMMIT_SHA}"

stages:
  # - test
  - build

# job1:
#   stage: test
#   script:
#     - echo "Building Docker image"
#     - docker build -t ganeshd2532/prod_data:$DOCKER_IMAGE .
#     - echo "Logging into Docker Hub"
#     - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
#     - docker push ganeshd2532/prod_data:$DOCKER_IMAGE

job2:
  stage: build
  script:
  - echo "Setting up SSH configuration"
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - echo "$PKEY_FILE" > ~/.ssh/id_rsa
  # - cat <<< "${PKEY_FILE}" > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - ssh-keyscan -H $ip >> ~/.ssh/known_hosts
  - chmod 600 ~/.ssh/known_hosts

  - echo "Testing SSH connection to $ip"
  - echo "Running remote deployment commands"
  - |
    ssh -i ~/.ssh/id_rsa -T azureuser@$ip <<EOF
      set -e  # Stop on error
      echo "Logging into Docker registry"
      echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY

      echo "Pulling Docker image"
      docker pull ganeshd2532/prod_data:$CI_COMMIT_SHA

      echo "Pruning unused containers and images"
      docker container prune -f
      docker image prune -f

      echo "Running Docker container"
      docker run -d -p 5432:5432 -p 5000:5000 -p 80:80 ganeshd2532/prod_data:$CI_COMMIT_SHA

      echo "Deployment complete"
    EOF

  - echo "Deployment completed successfully"
