image: ubuntu:20.04

workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: always

jjob1:
  stage: build
  script:
    - apt-get update
    - apt-get install -y openssh-server openssh-client
    - echo "Building the app"
    - echo "Fetching host key for $ip"
    - ssh-keyscan -H $ip >> ~/.ssh/known_hosts
    - ssh -i $PKEY_FILE -T azureuser@$ip
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker image ls
