image: ubuntu:20.04

workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: always

job1:
  stage: build
  script:
    - apt-get update
    - apt-get install -y openssh-server openssh-client
    - echo "Setting up SSH configuration"
    - mkdir -p ~/.ssh                         # Create the .ssh directory
    - chmod 700 ~/.ssh                        # Set correct permissions
    - ssh-keyscan -H $ip >> ~/.ssh/known_hosts # Add the host key
    - chmod 600 ~/.ssh/known_hosts            # Set correct permissions
    - echo "Connecting to $ip"
    - ssh -i $PKEY_FILE -T azureuser@$ip
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker image ls