image: docker:20.10

workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: always

job1:
  stage: test
  services:
    - docker:20.10-dind
  script:
    - echo "Building Docker image"
    - docker build . -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - echo "Logging into Docker Hub"
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA

job2:
  stage: build
  script:
  - echo "Setting up SSH configuration"
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - echo "$PKEY_FILE" > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - ssh-keyscan -H $ip >> ~/.ssh/known_hosts
  - chmod 600 ~/.ssh/known_hosts
  - echo "Testing SSH connection to $ip"
  - |
    if ! ssh -i ~/.ssh/id_rsa azureuser@$ip "echo 'SSH connection successful'"; then
      echo "ERROR: SSH connection failed" >&2
      exit 255
    fi
  - echo "Running remote deployment commands"
  - |
    ssh -i ~/.ssh/id_rsa -T azureuser@$ip <<EOF
      set -e
      echo "Logging into Docker registry"
      docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
      echo "Pulling Docker image"
      docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
      echo "Pruning unused containers and images"
      docker container prune -f
      docker image prune -f
      echo "Running Docker container"
      docker run -d -p 5432:5432 -p 5000:5000 -p 80:80 $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
      echo "Deployment complete"
    EOF
