image: ubuntu:20.04

workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: always
job1:
  stage: test
  script:
    - apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
    - docker --version
    - docker build . -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push docker.io/ganeshd2532/prod_data:$CI_COMMIT_SHA
job2:
  stage: build
  script:
    - apt-get update
    - docker --version
    - docker image ls
    - apt-get install -y openssh-server openssh-client
    - echo "Building the app"
    - echo "Setting up SSH configuration"
    - mkdir -p ~/.ssh                         
    - chmod 700 ~/.ssh                        
    - chmod 600 $PKEY_FILE                    
    - ssh-keyscan -H $ip >> ~/.ssh/known_hosts
    - chmod 600 ~/.ssh/known_hosts            
    - echo "Connecting to $ip"
    - ssh -i $PKEY_FILE -T azureuser@$ip "docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY"
    - ssh -i $PKEY_FILE -T azureuser@$ip "docker image ls"
    - ssh -i $PKEY_FILE -T azureuser@$ip "docker pull docker.io/ganeshd2532/prod_data:$CI_COMMIT_SHA"
    - ssh -i $PKEY_FILE -T azureuser@$ip "docker run -d -p 5432:5432 5000:5000 80:80 docker.io/ganeshd2532/prod_data:$CI_COMMIT_SHA"
    - echo "Build completed"
# /builds/my-first-grp7622121/Implementationa