image: ubuntu:latest
workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: always

job1:
  stage: build
  script:
    - echo "Building the app"
    - sudo apt-get update -y
    - sudo su
    - docker image ls
      
