job1:
  stage: build
  script:
    - apt-get update
    - apt-get install -y openssh-server openssh-client
    - echo "Building the app"
    - echo "Setting up SSH configuration"
    - mkdir -p ~/.ssh                         # Create the .ssh directory
    - chmod 700 ~/.ssh                        # Set correct permissions
    - chmod 600 $PKEY_FILE                    # Secure the private key file
    - ssh-keyscan -H $ip >> ~/.ssh/known_hosts # Add the host key
    - chmod 600 ~/.ssh/known_hosts            # Secure the known_hosts file
    - echo "Connecting to $ip"
    - ssh -i $PKEY_FILE -T azureuser@$ip
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker image ls