resources:
  - PVC.yaml
  - ../../base
  - base-service-patch.yaml
  - ingress-stage.yaml
namespaces:
  - stage
patchesStrategicMerge:
  - base-app-patch.yaml
  - SQL-patch.yaml
  - str-patch.yaml
  - sql-ser-patch.yaml
  - pv-patch.yaml
