apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-db-disk-stage
  namespace: stage
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/mnt/data"