apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-db-disk-test
  namespace: test
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/mnt/data"