apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-db-pvc-test
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-storage



