name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    
    # Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Cache Docker layers
    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-
          

    # Generate a dynamic tag using the GitHub run number or commit SHA
    - name: Generate Docker image tag
      id: tag
      run: echo "TAG=${{ github.sha }}" >> $GITHUB_ENV

    # Log in to Docker registry
    - name: Log in to Docker registry
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username="${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
        
    # Build the Docker image with dynamic tag
    - name: Build the Docker image
      run: |
        docker build -t prod_data:${{ env.TAG }} .

    # Tag the image for pushing to the private repository
    - name: Tag Docker image for private repo
      run: |
        docker tag prod_data:${{ env.TAG }} docker.io/ganeshd2532/prod_data:${{ env.TAG }}

    # Push the image to the private Docker repository
    - name: Push Docker image to private repo
      run: |
        docker push docker.io/ganeshd2532/prod_data:${{ env.TAG }}
