name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Generate Docker image tag
        id: tag
        run: echo "TAG=${{ github.sha }}" >> $GITHUB_ENV

      - name: Log in to Docker registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username="${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build the Docker image
        run: docker build -t prod_data:${{ env.TAG }} .

      - name: Tag Docker image for private repo
        run: docker tag prod_data:${{ env.TAG }} docker.io/ganeshd2532/prod_data:${{ env.TAG }}

      - name: Push Docker image to private repo
        run: docker push docker.io/ganeshd2532/prod_data:${{ env.TAG }}
